## this script is used to check the coverage of chrY from mybam.depth (generated by samtools depth function)
sampleList=$(cat sampleList.txt)
touch test_sex_result.txt
for sample in ${sampleList}
do
	echo ${sample}
	zcat ${sample}/mybam.depth.gz |awk 'BEGIN{FS="\t"}{if($1=="chrY" && $2>=2654980 && $2<=2655695){tmp+=$3}}END{printf("%.2f\n",tmp/715)}'
done >> test_sex_result.txt
